-- MySQL Schema for Nemesis Dashboard
-- Generated by SQLite to MySQL Export Tool

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- Table: assets
DROP TABLE IF EXISTS assets;
CREATE TABLE assets (
  `key` VARCHAR(255) PRIMARY KEY,
  json LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: regions
DROP TABLE IF EXISTS regions;
CREATE TABLE regions (
  region_key VARCHAR(255) PRIMARY KEY,
  code VARCHAR(255),
  province_name VARCHAR(255) NOT NULL,
  region_name VARCHAR(255) NOT NULL,
  region_type VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  feature_index INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: provinces
DROP TABLE IF EXISTS provinces;
CREATE TABLE provinces (
  province_key VARCHAR(255) PRIMARY KEY,
  code VARCHAR(255),
  province_name VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) NOT NULL,
  feature_index INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: packages
DROP TABLE IF EXISTS packages;
CREATE TABLE packages (
  id VARCHAR(255) PRIMARY KEY,
  source_id INT,
  schema_version VARCHAR(255) NOT NULL,
  owner_name TEXT NOT NULL,
  owner_type VARCHAR(255) NOT NULL,
  satker TEXT,
  package_name TEXT NOT NULL,
  procurement_type VARCHAR(255),
  procurement_method VARCHAR(255),
  location_raw TEXT NOT NULL,
  budget BIGINT,
  selection_date VARCHAR(255),
  funding_source TEXT,
  is_umkm INT NOT NULL,
  within_country INT NOT NULL,
  volume TEXT,
  work_description TEXT,
  specification TEXT,
  potential_waste DOUBLE NOT NULL,
  severity VARCHAR(50) NOT NULL,
  reason TEXT,
  is_mencurigakan INT,
  is_pemborosan INT,
  risk_score INT NOT NULL,
  active_tag_count INT NOT NULL,
  is_priority INT NOT NULL,
  is_flagged INT NOT NULL,
  mapped_region_count INT NOT NULL,
  inserted_order INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: package_regions
DROP TABLE IF EXISTS package_regions;
CREATE TABLE package_regions (
  package_id VARCHAR(255) NOT NULL,
  region_key VARCHAR(255) NOT NULL,
  PRIMARY KEY (package_id, region_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: package_provinces
DROP TABLE IF EXISTS package_provinces;
CREATE TABLE package_provinces (
  package_id VARCHAR(255) NOT NULL,
  province_key VARCHAR(255) NOT NULL,
  PRIMARY KEY (package_id, province_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: region_metrics
DROP TABLE IF EXISTS region_metrics;
CREATE TABLE region_metrics (
  region_key VARCHAR(255) PRIMARY KEY,
  total_packages INT NOT NULL,
  total_priority_packages INT NOT NULL,
  total_flagged_packages INT NOT NULL,
  total_potential_waste DOUBLE NOT NULL,
  total_budget BIGINT NOT NULL,
  avg_risk_score DOUBLE NOT NULL,
  max_risk_score INT NOT NULL,
  central_packages INT NOT NULL,
  provincial_packages INT NOT NULL,
  local_packages INT NOT NULL,
  other_packages INT NOT NULL,
  central_priority_packages INT NOT NULL,
  provincial_priority_packages INT NOT NULL,
  local_priority_packages INT NOT NULL,
  other_priority_packages INT NOT NULL,
  central_potential_waste DOUBLE NOT NULL,
  provincial_potential_waste DOUBLE NOT NULL,
  local_potential_waste DOUBLE NOT NULL,
  other_potential_waste DOUBLE NOT NULL,
  central_budget BIGINT NOT NULL,
  provincial_budget BIGINT NOT NULL,
  local_budget BIGINT NOT NULL,
  other_budget BIGINT NOT NULL,
  med_severity_packages INT NOT NULL,
  high_severity_packages INT NOT NULL,
  absurd_severity_packages INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: province_metrics
DROP TABLE IF EXISTS province_metrics;
CREATE TABLE province_metrics (
  province_key VARCHAR(255) PRIMARY KEY,
  total_packages INT NOT NULL,
  total_priority_packages INT NOT NULL,
  total_flagged_packages INT NOT NULL,
  total_potential_waste DOUBLE NOT NULL,
  total_budget BIGINT NOT NULL,
  avg_risk_score DOUBLE NOT NULL,
  max_risk_score INT NOT NULL,
  med_severity_packages INT NOT NULL,
  high_severity_packages INT NOT NULL,
  absurd_severity_packages INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Table: owner_metrics
DROP TABLE IF EXISTS owner_metrics;
CREATE TABLE owner_metrics (
  owner_type VARCHAR(255) NOT NULL,
  owner_name TEXT NOT NULL,
  total_packages INT NOT NULL,
  total_priority_packages INT NOT NULL,
  total_flagged_packages INT NOT NULL,
  total_potential_waste DOUBLE NOT NULL,
  total_budget BIGINT NOT NULL,
  med_severity_packages INT NOT NULL,
  high_severity_packages INT NOT NULL,
  absurd_severity_packages INT NOT NULL,
  PRIMARY KEY (owner_type, owner_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

SET FOREIGN_KEY_CHECKS = 1;