INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-aceh', '113', 'Aceh', 'Aceh', 0);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-bali', '277', 'Bali', 'Bali', 1);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-banten', '337', 'Banten', 'Banten', 2);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-bengkulu', '137', 'Bengkulu', 'Bengkulu', 3);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-di-yogyakarta', '283', 'DI Yogyakarta', 'DI Yogyakarta', 4);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-dki-jakarta', '275', 'DKI Jakarta', 'DKI Jakarta', 5);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-gorontalo', '6', 'Gorontalo', 'Gorontalo', 6);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-jambi', '131', 'Jambi', 'Jambi', 7);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-jawa-barat', '278', 'Jawa Barat', 'Jawa Barat', 8);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-jawa-tengah', '282', 'Jawa Tengah', 'Jawa Tengah', 9);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-jawa-timur', '280', 'Jawa Timur', 'Jawa Timur', 10);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kalimantan-barat', '440', 'Kalimantan Barat', 'Kalimantan Barat', 11);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kalimantan-selatan', '435', 'Kalimantan Selatan', 'Kalimantan Selatan', 12);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kalimantan-tengah', '437', 'Kalimantan Tengah', 'Kalimantan Tengah', 13);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kalimantan-timur', '441', 'Kalimantan Timur', 'Kalimantan Timur', 14);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kalimantan-utara', '442', 'Kalimantan Utara', 'Kalimantan Utara', 15);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kepulauan-bangka-belitung', '126', 'Kepulauan Bangka Belitung', 'Kepulauan Bangka Belitung', 16);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-kepulauan-riau', '140', 'Kepulauan Riau', 'Kepulauan Riau', 17);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-lampung', '162', 'Lampung', 'Lampung', 18);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-maluku-utara', '27', 'Maluku Utara', 'Maluku Utara', 19);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-maluku', '16', 'Maluku', 'Maluku', 20);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-nusa-tenggara-barat', '289', 'Nusa Tenggara Barat', 'Nusa Tenggara Barat', 21);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-nusa-tenggara-timur', '276', 'Nusa Tenggara Timur', 'Nusa Tenggara Timur', 22);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua-barat-daya', '508', 'Papua Barat Daya', 'Papua Barat Daya', 23);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua-barat', '500', 'Papua Barat', 'Papua Barat', 24);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua-pegunungan', '503', 'Papua Pegunungan', 'Papua Pegunungan', 25);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua-selatan', '495', 'Papua Selatan', 'Papua Selatan', 26);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua-tengah', '498', 'Papua Tengah', 'Papua Tengah', 27);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-papua', '496', 'Papua', 'Papua', 28);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-riau', '136', 'Riau', 'Riau', 29);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sulawesi-barat', '64', 'Sulawesi Barat', 'Sulawesi Barat', 30);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sulawesi-selatan', '4', 'Sulawesi Selatan', 'Sulawesi Selatan', 31);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sulawesi-tengah', '1', 'Sulawesi Tengah', 'Sulawesi Tengah', 32);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sulawesi-tenggara', '11', 'Sulawesi Tenggara', 'Sulawesi Tenggara', 33);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sulawesi-utara', '7', 'Sulawesi Utara', 'Sulawesi Utara', 34);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sumatera-barat', '124', 'Sumatera Barat', 'Sumatera Barat', 35);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sumatera-selatan', '130', 'Sumatera Selatan', 'Sumatera Selatan', 36);
INSERT INTO provinces (province_key, code, province_name, display_name, feature_index) VALUES ('province-sumatera-utara', '125', 'Sumatera Utara', 'Sumatera Utara', 37);
